load('figure_diff_acc_1000000user_l72.mat')
x= 5:5:100;
y=2:21;

figure(1)
plot(x,drawPointMtx1(2,y),'-+',...
    x,drawPointMtx1(3,y),'-o',...
    x,drawPointMtx1(4,y),'-*',...
    x,drawPointMtx1(6,y),'-x',...
    x,drawPointMtx1(8,y),'-s',...
    x,drawPointMtx1(9,y),'-d',...
   'LineWidth',2,'MarkerSize',8);
legend('LTE','Proposed-200pilot','Proposed-500pilot','Proposed-5000pilot','Proposed-50000pilot','CS-MUD');
xlabel('Number of active users')
ylabel('Pilot detection correct ratio')
grid on

figure(2)
plot(x,drawPointMtx3(2,y),'-+',...
    x,drawPointMtx3(3,y),'-o',...
    x,drawPointMtx3(4,y),'-*',...
    x,drawPointMtx3(6,y),'-x',...
    x,drawPointMtx3(8,y),'-s',...
    x,drawPointMtx3(9,y),'-d',...
   'LineWidth',2,'MarkerSize',8);
legend('LTE','Proposed-200pilot','Proposed-500pilot','Proposed-5000pilot','Proposed-50000pilot','CS-MUD');
xlabel('Number of active users')
ylabel('Data recovery correct ratio')
grid on

