load('figure_diff_l_1000000user_ac40.mat')
x= 64:2:96;
y=2:18;

figure(1)
plot(x,drawPointMtx3(3,y),'-+',...
    x,drawPointMtx3(4,y),'-o',...
    x,drawPointMtx3(5,y),'-*',...
    x,drawPointMtx3(6,y),'-x',...
    x,drawPointMtx3(7,y),'-s',...
    x,drawPointMtx3(8,y),'-d',...
   'LineWidth',2,'MarkerSize',8);
legend('LTE','Proposed-200pilot','Proposed-500pilot','Proposed-5000pilot','Proposed-50000pilot','CS-MUD');
xlabel('Length of the pilot')
ylabel('Data recovery correct ratio')
grid on

